### PR TITLE
1.20.4

### PR DESCRIPTION
**Pull request by sussyboiiii**

### CODE REVIEW

**Comment by LXYan2333** [comment]
the CI fails. 

```
An exception occurred applying plugin request [id: 'fabric-loom', version: '1.5-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Gradle (8.1.1). Gradle 8.3 or higher is required.
```

**Comment by sussyboiiii** [comment]
I used gradle 9

**Comment by LXYan2333** [comment]
another PR is accepted. thank you for your PR.

**Comment by LXYan2333** [comment]
you are listed as a contributer of this repo.

**Pull request closed without merging**
